create table _bag (id bigint identity not null, bkey varchar(255) check (bkey in ('TOKEN_SECRET')), bvalue varchar(255), primary key (id));
create table course (id bigint identity not null, teacher_id bigint not null, name varchar(255), type varchar(255) check (type in ('LECTURE','LAB')), primary key (id));
create table event_source_grade (created_at datetime2(6), created_by bigint, grade_id bigint, id bigint identity not null, creator varchar(255), payload varchar(max), source varchar(255), primary key (id));
create table event_source_student (created_at datetime2(6), created_by bigint, id bigint identity not null, student_id bigint, creator varchar(255), payload varchar(max), source varchar(255), primary key (id));
create table grade (grade float(53) not null, version smallint, course_id bigint not null, created_at datetime2(6), created_by bigint, id bigint identity not null, modified_at datetime2(6), modified_by bigint, student_id bigint not null, primary key (id));
create table program (id bigint identity not null, name varchar(255), primary key (id));
create table student (gpa float(53), version smallint, created_at datetime2(6), created_by bigint, id bigint identity not null, modified_at datetime2(6), modified_by bigint, program_id bigint not null, firstname varchar(255), lastname varchar(255), primary key (id));
create table users (id bigint identity not null, email varchar(255), firstname varchar(255), lastname varchar(255), password varchar(255) not null, role varchar(255) check (role in ('USER','ADMIN')), primary key (id));
alter table course add constraint FKbhmlx82vjuwypl8dmfnrbjfhu foreign key (teacher_id) references users;
alter table grade add constraint FK7e8ca7hfmrpruicqhocskjlf2 foreign key (course_id) references course;
alter table grade add constraint FK59tkftf69upthdepxtqdp2027 foreign key (created_by) references users;
alter table grade add constraint FKmhp5djm0p9gvjwe8ohbw4gfip foreign key (modified_by) references users;
alter table grade add constraint FK5secqnjjwgh9wxk4h1xwgj1n0 foreign key (student_id) references student;
alter table student add constraint FKjvaujae6vj4ofyh5y22gifukn foreign key (created_by) references users;
alter table student add constraint FKmvp5wgla3612qo33aphgocjcu foreign key (modified_by) references users;
alter table student add constraint FK9q4a7kjt0lk789n6orxc0xsf9 foreign key (program_id) references program;
